config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :todos
  resources :users
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: {minimum: 2}
  validates :due_date, presence: true

  belongs_to :user

  def due_today?
    due_date == Date.today
  end

  def self.of_user(user)
    where(user_id: user.id)
  end

  def self.overdue
    where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    where("due_date = ?", Date.today)
  end

  def self.due_later
    where("due_date > ?", Date.today)
  end

  def self.order_by_due_date
    order(:due_date)
  end

  def self.order_by_id
    order(:id)
  end

  def self.completed
    where(completed: true)
  end

  def self.add_task(h)
    create!(todo_text: h[:todo_text], due_date: (Date.today + h[:due_in_days]), completed: false)
  end

  def self.mark_as_complete(task_id)
    task = find(task_id)
    task.update(completed: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true

  has_secure_password
  has_many :todos

  def to_pleasant_string
    "#{id}. #{name} #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid Email or Password. Please Retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = current_user.todos.find(id)
    render plain: todo.to_pleasant_string
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def create
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">Welcome to the Todo homepage</h1>

<h3 class="Home-subHeading">
  If you are a new user, <%= link_to "sign-up here", new_user_path %>
</h3>

<h3 class="Home-subHeading">
  If you are an existing user, <%= link_to "sign-in here", new_sessions_path %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.first_name %>!
        <%= link_to "Sign-out", destroy_sessions_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"><%= section_title %></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
      <li class="TodoItem">
        <label class="TodoItem-container">

          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag "completed", todo.completed ? "0" : "1", todo.completed, class: "TodoItem-checkbox", onclick: "this.form.submit()" %>
          <% end %>

          <div class='<%= todo.completed ? "TodoItem-completed" : "" %>'><%= todo.todo_text %></div>

          <% if show_due_date %>
            <p class="TodoItem-date"><%= todo.due_date.to_s(:short) %></p>
          <% end %>

          <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>
            <%= image_submit_tag "delete.png", class: "TodoItem-delete" %>
          <% end %>

        </label>
      </li>
    <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
  <h1 class="TodoPage-title">My Todo-list</h1>
  <%= form_with(url: "/todos", method: "post", class: "AddTodo") do %>
    <%= text_field_tag "todo_text", nil, placeholder: "What's next?", class: "AddTodo-text" %>
    <%= date_field_tag "due_date", nil, class: "AddTodo-date" %>
    <%= submit_tag "Add", class: "AddTodo-button" %>
  <% end %>
  <%= render partial: "todo-section", locals: { section_title: "Overdue", todos: @todos.overdue.order_by_due_date, show_due_date: true } %>
  <%= render partial: "todo-section", locals: { section_title: "Due Today", todos: @todos.due_today.order_by_id, show_due_date: false } %>
  <%= render partial: "todo-section", locals: { section_title: "Due Later", todos: @todos.due_later.order_by_due_date, show_due_date: true } %>
</main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user!</p>

<section class="UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">First name: </p>
      <%= form.text_field :first_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Last name: </p>
      <%= form.text_field :last_name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-up!", class: "Form-submit" %>
    </div>
  <% end %>
</section>